version: '3'
services:
  institute-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  institute-mongosh:
    image: institute-mongosh
    depends_on:
      - institute-mongodb
    entrypoint: /bin/sh -c "sleep 10 && mongosh --host institute-mongodb -u root -p example --authenticationDatabase admin agile-learning-institute --eval 'load(\"/src/00-auto.js\")'"
