openapi: 3.0.3
info:
  title: curriculum
  version: 2.0.0.1
paths:
  /curriculum/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/curriculum'
components:
  schemas:
    curriculum:
      description: >-
        A Learning resource or other activity that is on a person's career or
        learning roadmap
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for a resource used by a person
          type: string
        resources:
          description: An array of resources
          items:
            properties:
              type:
                description: Type of the resource (topic or adhoc)
                enum:
                  - Topic
                  - Adhoc
                type: string
              resourceId:
                description: The ID of the resource assigned
                type: string
              topicId:
                description: The ID of the topic associated with the resource
                type: string
              name:
                description: The Resource Short Name for adhoc resources
                pattern: ^[ -~]{0,256}$
                type: string
              link:
                description: The Resource Link for adhoc resources
                pattern: >-
                  ^(https?:\/\/)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
                type: string
              roadmap:
                description: The top level grouping Now, Next, Later, Celebrated
                enum:
                  - Completed
                  - Now
                  - Next
                  - Later
                type: string
              status:
                description: Status of this resource
                enum:
                  - Assigned
                  - Started
                  - Completed
                type: string
              statusDate:
                description: Date the status was last changed
                type: string
              started:
                description: Date/time the link was clicked
                type: string
              completed:
                description: Date/time the item was checked off
                type: string
            additionalProperties: false
            type: object
          type: array
      additionalProperties: false
      type: object
