openapi: 3.0.3
info:
  title: encounters
  version: 1.0.0.1
paths:
  /encounters/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/encounters'
components:
  schemas:
    encounters:
      description: An encounter between a member and a mentor
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for an encounter
          type: string
        version:
          description: Scehma Version (only on Version document)
          maxLength: 20
          type: string
        date:
          description: The date/time of the encounter
          type: string
        personId:
          description: The ID of the member in the encounter
          type: string
        mentorId:
          description: The ID of the mentor in the encounter
          type: string
        planId:
          description: The ID of the plan used to start this encounter
          type: string
        status:
          description: The status of this encounter
          type: string
        observations:
          description: a list of observations
          items:
            description: An prompt to uncover information, and the observation made
            properties:
              type:
                description: The type of observation control, from an enumerated list
                type: string
              prompt:
                description: The question asked
                maxLength: 256
                type: string
              options:
                description: >-
                  The options for an answer (on radio and check type
                  observations)
                items:
                  type: string
                type: array
              values:
                description: >-
                  The values selected or entered (will be a single value for
                  radio and text observations)
                items:
                  type: string
                type: array
            type: object
          type: array
      additionalProperties: false
      type: object
