openapi: 3.0.3
info:
  title: partners
  version: 1.1.3.1
paths:
  /partners/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/partners'
components:
  schemas:
    partners:
      required:
        - _id
        - name
      properties:
        _id:
          description: The unique identifier for a partner
          type: string
        name:
          description: Partner name
          pattern: ^[ -~]{0,256}$
          type: string
        description:
          description: Description of the partner
          pattern: ^[ -~]{0,256}$
          type: string
        status:
          description: The status of this partnership
          enum:
            - Active
            - Inactive
            - Archived
          type: string
        url:
          description: Partner Company website
          pattern: >-
            ^(https?:\/\/)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
          type: string
        contacts:
          description: Array of contacts associated with this partner
          items:
            type: string
          type: array
        lastSaved:
          description: Change tracking breadcrumb
          properties:
            fromIp:
              description: Http Request remote IP address
              pattern: >-
                ^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
          type: object
      type: object
