openapi: 3.0.3
info:
  title: paths
  version: 1.0.0.1
paths:
  /paths/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paths'
components:
  schemas:
    paths:
      description: Path - Segment grouping
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for the grouping
          type: string
        version:
          description: Scehma Version (only on Version document
          maxLength: 20
          type: string
        status:
          description: The status of this Path
          type: string
        name:
          description: The Path Name
          maxLength: 64
          type: string
        segments:
          items:
            description: A grouping of Topics within a Path
            properties:
              name:
                description: The Segment Name
                maxLength: 64
                type: string
              topics:
                description: The list of topics in this Segment
                items:
                  description: The Topic ID
                  type: string
                type: array
            type: object
          type: array
      additionalProperties: false
      type: object
