openapi: 3.0.3
info:
  title: paths
  version: 1.0.0.1
paths:
  /paths/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paths'
components:
  schemas:
    paths:
      description: Path - Segment grouping
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for the grouping
          type: string
        status:
          description: The status of this Path
          enum:
            - Active
            - Archived
          type: string
        name:
          description: The Path Name
          pattern: ^[ -~]{0,256}$
          type: string
        segments:
          items:
            description: A grouping of Topics within a Path
            properties:
              name:
                description: The Segment Name
                pattern: ^[ -~]{0,256}$
                type: string
              topics:
                description: The list of topics in this Segment
                items:
                  description: The Topic ID
                  type: string
                type: array
            type: object
          type: array
        lastSaved:
          description: Change tracking breadcrumb
          properties:
            fromIp:
              description: Http Request remote IP address
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
          type: object
      additionalProperties: false
      type: object
