openapi: 3.0.3
info:
  title: resources
  version: 1.0.3.1
paths:
  /resources/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resources'
components:
  schemas:
    resources:
      description: A Learning resource
      required:
        - _id
      properties:
        _id:
          description: The unique identifier for a resource
          type: string
        name:
          description: The Resource Shrot Name (slug)
          pattern: ^[^\s]{0,32}$
          type: string
        status:
          description: The status of this resource
          enum:
            - Active
            - Archived
          type: string
        description:
          description: The Resource description
          pattern: ^[ -~]{0,256}$
          type: string
        duration:
          description: The estimated time in minutes to consume this resource
          minimum: 1
          maximum: 2880
          type: number
        link:
          description: Link to Resource, must be https
          pattern: >-
            ^(https?:\/\/)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
          type: string
        skills:
          description: The list of skills this resource contributes to
          items:
            type: string
          type: array
        tags:
          description: Tags to assist with classification of this resource
          items:
            enum:
              - $
              - Article
              - Book
              - Exam
              - Interactive
              - Lecture
              - Lesson
              - Reference
              - Tutorial
              - User Guide
              - Video
              - UI/UX
              - API
              - Data
              - SRE
            type: string
          type: array
        lastSaved:
          description: Tracking breadcrumb
          properties:
            fromIp:
              description: Http Request remote IP address
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
          type: object
      additionalProperties: false
      type: object
