openapi: 3.0.3
info:
  title: resources
  version: 1.0.3.1
paths:
  /resources/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resources'
components:
  schemas:
    resources:
      description: A Learning resource
      required:
        - _id
        - name
        - link
      properties:
        _id:
          description: The unique identifier for a resource
          type: string
        version:
          description: Scehma Version (only on Version document
          maxLength: 20
          type: string
        name:
          description: The Resource Shrot Name (slug)
          maxLength: 64
          type: string
        status:
          description: The status of this resource
          type: string
        description:
          description: The Resource description
          maxLength: 256
          type: string
        duration:
          description: The estimated time in minutes to consume this resource
          minimum: 1
          maximum: 2880
          type: number
        link:
          description: Link to Resource, must be https
          maxLength: 256
          pattern: >-
            ^https:\/\/([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
          type: string
        skills:
          description: The list of skills this resource contributes to
          items:
            type: string
          type: array
        tags:
          description: Tags to assist with classification of this resource
          items:
            type: string
          type: array
      additionalProperties: false
      type: object
