openapi: 3.0.3
info:
  title: topics
  version: 2.0.3.1
paths:
  /topics/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/topics'
components:
  schemas:
    topics:
      description: A Learning Topic
      required:
        - _id
        - name
      properties:
        _id:
          description: The Topic ID
          type: string
        name:
          description: The Topic Name
          pattern: ^[ -~]{0,256}$
          type: string
        status:
          description: The status of this topic
          enum:
            - Active
            - Archived
          type: string
        description:
          description: The Topic overview paragraph
          pattern: ^[ -~]{0,256}$
          type: string
        category:
          description: >-
            A simple categorization of topics based on ITIL and ITSM best
            practices
          enum:
            - Foundations of ITSM
            - Design and Development
            - Infrastructure and Operations
            - Networking and Security
            - Development Tools and Practices
            - Data Management
            - Continuous Integration and Deployment
            - Monitoring and Performance
          type: string
        skills:
          description: The list of skills related to this topic
          items:
            type: string
          type: array
        resources:
          description: List of resources related to this topic
          items:
            type: string
          type: array
        lastSaved:
          description: Tracking breadcrumb
          properties:
            fromIp:
              description: Http Request remote IP address
              pattern: >-
                ^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$
              type: string
            byUser:
              description: UUID Of User
              type: string
            atTime:
              description: The date-time when last updated
              type: string
            correlationId:
              description: The logging correlation ID of the update transaction
              type: string
          additionalProperties: false
          type: object
      additionalProperties: false
      type: object
