openapi: 3.0.3
info:
  title: people
  version: 1.4.5.1
paths:
  /people/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/people'
components:
  schemas:
    people:
      required:
        - _id
        - userName
      properties:
        _id:
          description: The unique identifier for a person
          type: string
        name:
          description: VERSION document only
          maxLength: 32
          type: string
        version:
          description: VERSION document only
          maxLength: 20
          type: string
        userName:
          description: Username
          pattern: ^[^\s]{0,64}$
          type: string
        firstName:
          description: The persons first name
          pattern: ^[^\s]{0,64}$
          type: string
        lastName:
          description: The persons last name
          pattern: ^[^\s]{0,64}$
          type: string
        description:
          description: Notes or other descriptive text
          maxLength: 256
          type: string
        status:
          description: The status of this member
          type: string
        roles:
          description: RBAC Roles for this person
          items:
            type: string
          type: array
        member:
          description: Is this person a Member
          type: boolean
        mentor:
          description: Is this person a Mentor
          type: boolean
        donor:
          description: Is this person a Donor
          type: boolean
        contact:
          description: Is this person a Partner Contact
          type: boolean
        mentorId:
          description: the _id of this persons Mentor if they have one
          type: string
        partnerId:
          description: the _id of this persons partner (contacts and members)
          type: string
        title:
          description: The person's title in the career path
          type: string
        cadence:
          description: This person's preferred meeting cadence
          type: string
        eMail:
          description: The person's eMail address
          maxLength: 256
          pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
          type: string
        gitHub:
          description: The person's gitHub User ID
          pattern: ^[^\s]{0,32}$
          type: string
        phone:
          description: The person's phone number
          pattern: ^\d{3}[-.\s]?\d{3}[-.\s]?\d{4}$
          type: string
        device:
          description: The type of PC this person is using
          type: string
        location:
          description: The location where this person lives
          maxLength: 64
          type: string
      additionalProperties: false
      type: object
