openapi: 3.0.3
info:
  title: plans
  version: 1.0.0.1
paths:
  /plans/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/plans'
components:
  schemas:
    plans:
      description: A plan for an encounter between a member and a mentor
      required:
        - _id
        - name
      properties:
        _id:
          description: The unique identifier for an encounter plan
          type: string
        version:
          description: Scehma Version (only on Version document)
          maxLength: 20
          type: string
        name:
          description: The short name of the plan
          maxLength: 32
          type: string
        description:
          description: Description of the Plan
          maxLength: 256
          type: string
        status:
          description: The status of this plan
          type: string
        checklist:
          description: a checklist of planned observations
          items:
            description: >-
              An prompt to uncover information, and possible options to
              accelerate note taking
            properties:
              type:
                description: The type of observation control, from an enumerated list
                type: string
              prompt:
                description: The question asked
                maxLength: 256
                type: string
              options:
                description: >-
                  The options for an answer (on radio and check type
                  observations)
                items:
                  type: string
                type: array
            type: object
          type: array
      additionalProperties: false
      type: object
