openapi: 3.0.3
info:
  title: topics
  version: 2.0.3.1
paths:
  /topics/:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/topics'
components:
  schemas:
    topics:
      description: A Learning Topic
      required:
        - _id
        - name
      properties:
        _id:
          description: The Topic ID
          type: string
        version:
          description: Scehma Version (only on Version document
          maxLength: 20
          type: string
        name:
          description: The Topic Name
          maxLength: 128
          type: string
        status:
          description: The status of this topic
          type: string
        description:
          description: The Topic overview paragraph
          maxLength: 512
          type: string
        category:
          description: >-
            A simple categorization of topics based on ITIL and ITSM best
            practices
          type: string
        skills:
          description: The list of skills related to this topic
          items:
            type: string
          type: array
        resources:
          description: List of resources related to this topic
          items:
            type: string
          type: array
      additionalProperties: false
      type: object
