name: Build and Push Docker Image
run-name: ${{ github.actor }} ran Build and Push

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/docker/Dockerfile 
          secrets: "github_token=${{ secrets.GITHUB_TOKEN }}"
          push: true
          tags: ghcr.io/agile-learning-institute/institute-mongosh:latest
